spring.application.name=franchise-api
spring.profiles.active=test

# In-memory configuration for testing
aws.region=us-east-2
aws.dynamodb.table-name=test-franchise-table

# Mock AWS credentials
aws.accessKeyId=test
aws.secretKey=test
aws.endpoint-override=http://localhost:8000
